name: 构建 EasyTier Docker 镜像

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v6  # 升级v6

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v4  # 升级v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v4  # 升级v4，消除Node警告

      # 登录 Docker Hub（修复登录错误）
      - name: 登录 Docker Hub
        uses: docker/login-action@v4  # 升级v4
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # 构建并推送镜像
      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 镜像名称：你的Docker用户名/easytier:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/easytier:latest
